Disable job completion check in ansible-run.yml
Comment out the job completion wait logic in the Ansible workflow.

diff --git a/.github/workflows/ansible-run.yml b/.github/workflows/ansible-run.yml
--- a/.github/workflows/ansible-run.yml
+++ b/.github/workflows/ansible-run.yml
@@ -28,7 +28,8 @@ jobs:
                      --data '{"inventory": "Webserver PROD"}'\
                      "${{ vars.ANSIBLE_CONTROLLER_URL }}/api/controller/v2/job_templates/Deploy%20Javascript%20TODO%20List%20Application/launch" \
                     ) 
-          
+          # Debug full response
+          echo $RESPONSE
           # Parse to get what job was started
           JOB_ID=$(echo $RESPONSE | jq -r '.job')
           echo El job id es $JOB_ID
@@ -36,34 +37,34 @@ jobs:
           # Pass variables to next step
           echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV
 
-      - name: Wait for completion of deploy job
-        run: |
-          # Print where to find the logs
-          echo Examine job progress at "${{ vars.ANSIBLE_CONTROLLER_URL }}/#/jobs/playbook/${JOB_ID}"
+      # - name: Wait for completion of deploy job
+      #   run: |
+      #     # Print where to find the logs
+      #     echo Examine job progress at "${{ vars.ANSIBLE_CONTROLLER_URL }}/#/jobs/playbook/${JOB_ID}"
           
-          # Query the job API to see if it has finished
-          JOB_STATUS="new"
-          while [[ "$JOB_STATUS" == "new" || "$JOB_STATUS" == "pending" || "$JOB_STATUS" == "running"  || "$JOB_STATUS" == "waiting" ]]; do
-            sleep 10  # Poll every 30 seconds; adjust as necessary
-            RESPONSE=$(curl -s -k -A "nonstandardUA" -X GET "${{ vars.ANSIBLE_CONTROLLER_URL }}/api/controller/v2/jobs/$JOB_ID/" -H "Authorization: Bearer ${{ secrets.ANSIBLE_TOKEN }}")
-            JOB_STATUS=$(echo $RESPONSE | jq -r '.status')
-            echo "Job status: $JOB_STATUS"
-          done
+      #     # Query the job API to see if it has finished
+      #     JOB_STATUS="new"
+      #     while [[ "$JOB_STATUS" == "new" || "$JOB_STATUS" == "pending" || "$JOB_STATUS" == "running"  || "$JOB_STATUS" == "waiting" ]]; do
+      #       sleep 10  # Poll every 30 seconds; adjust as necessary
+      #       RESPONSE=$(curl -s -k -A "nonstandardUA" -X GET "${{ vars.ANSIBLE_CONTROLLER_URL }}/api/controller/v2/jobs/$JOB_ID/" -H "Authorization: Bearer ${{ secrets.ANSIBLE_TOKEN }}")
+      #       JOB_STATUS=$(echo $RESPONSE | jq -r '.status')
+      #       echo "Job status: $JOB_STATUS"
+      #     done
 
-          if [[ "$JOB_STATUS" == "successful" ]]; then
-            echo "Job completed successfully."
-            exit 0
-          else
-            # Handle the job failure case, print what jobs have failed
-            echo "Job failed with status $JOB_STATUS."
+      #     if [[ "$JOB_STATUS" == "successful" ]]; then
+      #       echo "Job completed successfully."
+      #       exit 0
+      #     else
+      #       # Handle the job failure case, print what jobs have failed
+      #       echo "Job failed with status $JOB_STATUS."
 
-            # Report failed hosts
-            # Get job stdout to get the summary part
-            RESPONSE=$(curl -s -k -A "nonstandardUA" -X GET "${{ vars.ANSIBLE_CONTROLLER_URL }}/api/controller/v2/jobs/$JOB_ID/stdout/?format=txt" -H "Authorization: Bearer ${{ secrets.ANSIBLE_TOKEN }}")
+      #       # Report failed hosts
+      #       # Get job stdout to get the summary part
+      #       RESPONSE=$(curl -s -k -A "nonstandardUA" -X GET "${{ vars.ANSIBLE_CONTROLLER_URL }}/api/controller/v2/jobs/$JOB_ID/stdout/?format=txt" -H "Authorization: Bearer ${{ secrets.ANSIBLE_TOKEN }}")
 
-            # Print host summary from STDOUT
-            echo "Please examine failed hosts manually:"
-            echo "$RESPONSE" | awk '/PLAY RECAP/{flag=1} flag' | grep -E '(failed=[1-9])|(unreachable=[1-9])'
-            echo "====================================="
-            exit 1
-          fi
+      #       # Print host summary from STDOUT
+      #       echo "Please examine failed hosts manually:"
+      #       echo "$RESPONSE" | awk '/PLAY RECAP/{flag=1} flag' | grep -E '(failed=[1-9])|(unreachable=[1-9])'
+      #       echo "====================================="
+      #       exit 1
+      #     fi
